# 第二次课作业

In [2]:
import numpy as np

（1）创建一个1到10的数组，然后逆序输出。

In [5]:
a = np.arange(1,11)
a[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

（2）创建一个长度为20的全1数组，然后变成一个4×5的二维矩阵并转置。

In [9]:
a = np.ones(20,dtype=int)
a = a.reshape(4,5)
a.T

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

（3）创建一个3x3x3的随机数组。
(提示: np.random.random)

In [74]:
np.random.randint(1,100,27).reshape(3,3,3)
np.random.random((3,3,3))

array([[[0.99323223, 0.86199395, 0.81374667],
        [0.13567963, 0.62457588, 0.95628037],
        [0.11295453, 0.71324936, 0.10760678]],

       [[0.91182911, 0.05209577, 0.2811764 ],
        [0.25508569, 0.34255913, 0.12064423],
        [0.88538519, 0.50113221, 0.18870452]],

       [[0.85860395, 0.94335718, 0.16080915],
        [0.18278232, 0.21564277, 0.42285299],
        [0.97223319, 0.72741274, 0.39610774]]])

（4）从1到10中随机选取10个数，构成一个长度为10的数组，并将其排序。获取其最大值最小值，求和，求方差。

In [77]:
b = np.sort(np.random.randint(1,11,10))
print(b,b.max(),b.sum(),b.var())

[ 1  1  2  5  5  6  6  7  9 10] 10 52 8.76


（5）从1到10中随机选取10个数，构成一个长度为10的数组，选出其中的奇数。

In [82]:
a = np.random.randint(1,11,10)
a[np.where((a%2)==1)]
a[a%2==1]

array([3, 7, 9])

（6）生成0到100，差为5的一个等差数列，然后将数据类型转化为整数。

In [83]:
a = np.arange(0,101,5,dtype=int)
a.astype(float)

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

（7）从1到10中随机选取10个数，大于3和小于8的取负数。

In [87]:
a = np.random.randint(1,10,10)
a[np.where((a>3)&(a<8))] *= -1
a[(a>3)&(a<8)] *= -1
a

array([-4, -7,  1,  3, -7,  9,  9,  9,  3,  3])

（8）在数组[1, 2, 3, 4, 5]中相邻两个数字中间插入1个0。

In [86]:
a = np.array([1,2,3,4,5])
b = np.zeros(9,dtype=int)
b[::2] = a
b

array([1, 0, 2, 0, 3, 0, 4, 0, 5])

（9）新建一个5乘5的随机二位数组，交换其中两行？比如交换第一二行。

In [95]:
a = np.random.randint(1,10,(5,5))
print(a)
a = a[[1,0,2,3,4]]
a

[[4 5 8 9 3]
 [8 2 3 1 4]
 [6 1 4 3 8]
 [8 7 4 3 2]
 [6 3 7 9 1]]


array([[8, 2, 3, 1, 4],
       [4, 5, 8, 9, 3],
       [6, 1, 4, 3, 8],
       [8, 7, 4, 3, 2],
       [6, 3, 7, 9, 1]])

（10）把一个10\*2的随机生成的笛卡尔坐标转换成极坐标。

（11）创建一个长度为10并且除了第五个值为1其余的值为2的向量。

In [64]:
a = np.random.randint(1,11,10)
a.fill(2)
a[4] = 1
a

array([2, 2, 2, 2, 1, 2, 2, 2, 2, 2])

（12）创建一个长度为10的随机向量，并求其累计和。

In [96]:
np.random.randint(1,11,10).cumsum()


array([ 6,  7, 14, 21, 29, 34, 35, 44, 49, 56])

（13）将数组中的所有奇数替换成-1。

In [62]:
a = np.random.randint(1,11,10)
a[np.where((a%2)==1)] = -1
a


array([-1,  6, -1, -1,  4,  4,  8,  2, 10,  2])

（14）构造两个4乘3的二维数组，按照3种方法进行连接？

In [73]:
a = np.arange(12).reshape(4,3)
b = np.arange(12,24).reshape(4,3)
print(np.vstack((a,b)),"\n",np.dstack((a,b)),"\n",np.hstack((a,b)))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]] 
 [[[ 0 12]
  [ 1 13]
  [ 2 14]]

 [[ 3 15]
  [ 4 16]
  [ 5 17]]

 [[ 6 18]
  [ 7 19]
  [ 8 20]]

 [[ 9 21]
  [10 22]
  [11 23]]] 
 [[ 0  1  2 12 13 14]
 [ 3  4  5 15 16 17]
 [ 6  7  8 18 19 20]
 [ 9 10 11 21 22 23]]


（15）获取数组 a 和 b 中的共同项（索引位置相同，值也相同）。
a = np.array([1,2,3,2,3,4,3,4,5,6])，b = np.array([7,2,10,2,7,4,9,4,9,8])

In [98]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = a-b
a[c==0]


array([2, 2, 4, 4])

（16）从数组 a 中提取 5 和 10 之间的所有项。a=np.array([7,2,10,2,7,4,9,4,9,8])

In [60]:
a=np.array([7,2,10,2,7,4,9,4,9,8])
a[np.where((a>=5)&(a<=10))]

array([ 7, 10,  7,  9,  9,  8])